export const BUSQUEDA = 'BUSQUEDA'
export const FILTER = 'FILTRAR'
export const ORDER = 'ORDER'
export const BUSCARALL = 'BUSCARALL'
export const GENRES = 'GENRES' 
export const COPY = 'COPY'
export const INDIVIDUALBUSQUEDA = 'INDIVIDUALBUSQUEDA'
export const INDIVIDUALAPI = 'INDIVIDUALAPI'
